BTW = 9

OLIBOLLEN = 1.15
OLIBOLLEN_GEEN_BTW =  OLIBOLLEN-OLIBOLLEN/100*BTW
APPELFLAP = 1.60
APPELFLAP_GEEN_BTW = APPELFLAP-APPELFLAP/100*BTW
OLIBOLLEN_ZAK = 10.00 
OLIBOLLEN_ZAK_GEEN_BTW = OLIBOLLEN_ZAK-OLIBOLLEN_ZAK/100*BTW
KORTING = 7.5

korting = False
verschil = 0
active_korting = False

text = '------ [UW BESTELLING] ------'